# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ffc644c2e1e7705390ebef7129ef3d1b25d19dcd381d1d8f5c7b6c614a77a46a3889d2abd543d2899a367b2a05fa9d17464617031d3fc42cd6dca340ff3e9f11

test:
  secret_key_base: f45022e83134a13aadb90dc2fb696f7008add7d8ce32dbc21c432064c5157039eaa7a673581a0cb34110d599b62b17fc3d9bc9adf01fd6a8af7a68735c95f0b3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
